### ISSUE TITLE
Prendre en compte les espaces

### ISSUE THREAD

**Issue by Skytowz** [Guilamb/interspecies-reviewer#2]
Lorsque l'on souhaite envoyé un lien précédé d'un message, si il y a un espace ou un retour à la ligne, le lien n'est pas pris en compte

Exemple : 
`TEST1 https://twitter.com/PC_Focus_/status/1764949897621442930`
TEST2 
https://twitter.com/PC_Focus_/status/1764949897621442930

**Comment by Guilamb** [comment]
It seems that adding a space before a link is causing it to be misinterpreted.
For example :

This would work
```
Hellohttps://link.com`
```

However this doesn't
```
Hello https://link.com
```

---
Les espaces précédant le lien semblent ne pas être interpretés correctement
Par exemple :

Ceci fonctionne 
```
Hellohttps://link.com
````

Quand ceci non
```
Hello https://link.com
```
